on:
    schedule:
      - cron: '*/1 * * * *'  # Every 10 minutes
  jobs:
    keepalive:
      runs-on: ubuntu-latest
      steps:
        - run: curl -s "https://gamernestt-test-vx2xjqnhnr6.ws-us118.gitpod.io/" > /dev/null
